name: Build Priyanshu APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Buildozer Dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build APK with Buildozer
      run: |
        YES=1 buildozer -v android debug

    - name: Upload Finished APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Priyanshu-Core-Kit-APK
        path: bin/*.apk
